title: Jingyi Cai # your name (or website title) here
logo: "/images/new_icon.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Spacial Data Analyst 
  <br><br>
  Urban Designer
  <br><br>
  <a href="https://www.linkedin.com/in/jingyi-cai-9b9085255/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here